keys:
  - &admin_kuri 4DF35290882C2927ACD88A4F6FCA9BE19FC69E48
  - &server_clochette age18594hnd4mk3736a36a5fqc5w55sanac86tv8du0hz67rfk558srs3y9jwa
creation_rules:
  - path_regex: secrets/kuri_exampleHost.yaml$
    key_groups:
    - pgp:
      - *admin_kuri
  - path_regex: secrets/clochette.yaml
    key_groups:
    - age:
      - *server_clochette
